import { copyFile, stat, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

import { logger } from './logger'

import type { Collections, Output } from './types'

const isProduction = process.env.NODE_ENV === 'production'

export const createEmittedMap = (): Map<string, string> => new Map()

/**
 * emit file if content changed, reduce disk IO and improve fast refresh in app
 * @param path file path
 * @param content file data
 * @param emitted map of previously emitted content
 * @param log log message
 */
export const emit = async (path: string, content: string, emitted: Map<string, string>, log?: string): Promise<void> => {
  if (emitted.get(path) === content) {
    logger.log(`skipped write '${path}' with same content`)
    return
  }
  await writeFile(path, content)
  logger.log(log ?? `wrote '${path}' with ${content.length} bytes`)
  emitted.set(path, content)
}

/**
 * output entry file
 * @param dest output destination directory
 * @param configPath resolved config file path
 * @param collections collection options
 * @param emitted map of previously emitted content
 */
export const outputEntry = async (dest: string, format: Output['format'], configPath: string, collections: Collections, emitted: Map<string, string>): Promise<void> => {
  const begin = performance.now()

  const configModPath = relative(dest, configPath).replace(/\\/g, '/')

  const entry: string[] = []
  const dts: string[] = [`import type __vc from '${configModPath}'\n`]
  dts.push('type Collections = typeof __vc.collections\n')

  Object.entries(collections).map(([name, collection]) => {
    if (format === 'cjs') {
      entry.push(`exports.${name} = require('./${name}.json')`)
    } else {
      entry.push(`export { default as ${name} } from './${name}.json' with { type: 'json' }`)
    }
    dts.push(`export type ${collection.name} = Collections['${name}']['schema']['_output']`)
    dts.push(`export declare const ${name}: ${collection.name + (collection.single ? '' : '[]')}\n`)
  })

  const banner = '// This file is generated by RedStraw\n\n'

  const entryFile = join(dest, 'index.js')
  await emit(entryFile, banner + entry.join('\n'), emitted, `created entry file in '${entryFile}'`)

  const dtsFile = join(dest, 'index.d.ts')
  await emit(dtsFile, banner + dts.join('\n'), emitted, `created entry dts file in '${dtsFile}'`)

  logger.log(`output entry file in '${dest}'`, begin)
}

/**
 * output all built result
 * @param dest output destination directory
 * @param result all built result
 * @param emitted map of previously emitted content
 */
export const outputData = async (dest: string, result: Record<string, any>, emitted: Map<string, string>): Promise<void> => {
  const begin = performance.now()
  const logs: string[] = []
  await Promise.all(
    Object.entries(result).map(async ([name, data]) => {
      if (data == null) return
      const target = join(dest, name + '.json')
      const content = isProduction ? JSON.stringify(data) : JSON.stringify(data, null, 2)
      const count = Array.isArray(data) ? data.length : 1
      await emit(target, content, emitted, `wrote '${target}' with ${count} ${name}`)
      logs.push(`${count} ${name}`)
    })
  )
  logger.log(`output ${logs.join(', ')}`, begin)
}

/**
 * output all collected assets
 * @param dest output destination directory
 * @param assets all collected assets
 * @param emitted map of previously emitted content
 */
export const outputAssets = async (dest: string, assets: Map<string, string>, emitted: Map<string, string>): Promise<void> => {
  const begin = performance.now()
  let count = 0
  await Promise.all(
    Array.from(assets.entries()).map(async ([name, from]) => {
      const { mtimeMs } = await stat(from)
      const key = `${name}:${mtimeMs}`
      if (emitted.get(name) === key) {
        logger.log(`skipped copy '${name}' (unchanged)`)
        return
      }
      await copyFile(from, join(dest, name))
      emitted.set(name, key)
      count++
    })
  )
  logger.log(`output ${count} assets`, begin)
}
