name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'Ajmalleonard/redstraw'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm -r publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
